// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.27.5
// source: reminderService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReminderModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"title" form:"title"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty" form:"title"`
	// @inject_tag: json:"end_time" form:"end_time"
	EndTime int64 `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty" form:"end_time"`
}

func (x *ReminderModel) Reset() {
	*x = ReminderModel{}
	mi := &file_reminderService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderModel) ProtoMessage() {}

func (x *ReminderModel) ProtoReflect() protoreflect.Message {
	mi := &file_reminderService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderModel.ProtoReflect.Descriptor instead.
func (*ReminderModel) Descriptor() ([]byte, []int) {
	return file_reminderService_proto_rawDescGZIP(), []int{0}
}

func (x *ReminderModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReminderModel) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"uid" form:"uid"
	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" form:"uid"`
	// @inject_tag: json:"dead_line" form:"dead_line"
	DeadLine int64 `protobuf:"varint,2,opt,name=dead_line,json=deadLine,proto3" json:"dead_line,omitempty" form:"dead_line"`
}

func (x *ReminderRequest) Reset() {
	*x = ReminderRequest{}
	mi := &file_reminderService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderRequest) ProtoMessage() {}

func (x *ReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminderService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderRequest.ProtoReflect.Descriptor instead.
func (*ReminderRequest) Descriptor() ([]byte, []int) {
	return file_reminderService_proto_rawDescGZIP(), []int{1}
}

func (x *ReminderRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReminderRequest) GetDeadLine() int64 {
	if x != nil {
		return x.DeadLine
	}
	return 0
}

type GetTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"uid" form:"uid"
	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" form:"uid"`
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_reminderService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reminderService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_reminderService_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ReminderListRespose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"task_list"
	TaskList []*ReminderModel `protobuf:"bytes,1,rep,name=task_list,json=taskList,proto3" json:"task_list,omitempty"`
	// @inject_tag: json:"count"
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// @inject_tag: json:"code"
	Code uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ReminderListRespose) Reset() {
	*x = ReminderListRespose{}
	mi := &file_reminderService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReminderListRespose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReminderListRespose) ProtoMessage() {}

func (x *ReminderListRespose) ProtoReflect() protoreflect.Message {
	mi := &file_reminderService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReminderListRespose.ProtoReflect.Descriptor instead.
func (*ReminderListRespose) Descriptor() ([]byte, []int) {
	return file_reminderService_proto_rawDescGZIP(), []int{3}
}

func (x *ReminderListRespose) GetTaskList() []*ReminderModel {
	if x != nil {
		return x.TaskList
	}
	return nil
}

func (x *ReminderListRespose) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReminderListRespose) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_reminderService_proto protoreflect.FileDescriptor

var file_reminderService_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x22, 0x40, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x61, 0x64,
	0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x61,
	0x64, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x75, 0x0a, 0x13, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x08, 0x74, 0x61,
	0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x32, 0xa8, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x61, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reminderService_proto_rawDescOnce sync.Once
	file_reminderService_proto_rawDescData = file_reminderService_proto_rawDesc
)

func file_reminderService_proto_rawDescGZIP() []byte {
	file_reminderService_proto_rawDescOnce.Do(func() {
		file_reminderService_proto_rawDescData = protoimpl.X.CompressGZIP(file_reminderService_proto_rawDescData)
	})
	return file_reminderService_proto_rawDescData
}

var file_reminderService_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reminderService_proto_goTypes = []any{
	(*ReminderModel)(nil),       // 0: services.ReminderModel
	(*ReminderRequest)(nil),     // 1: services.ReminderRequest
	(*GetTaskRequest)(nil),      // 2: services.GetTaskRequest
	(*ReminderListRespose)(nil), // 3: services.ReminderListRespose
}
var file_reminderService_proto_depIdxs = []int32{
	0, // 0: services.ReminderListRespose.task_list:type_name -> services.ReminderModel
	1, // 1: services.ReminderService.UpdateDeadLine:input_type -> services.ReminderRequest
	2, // 2: services.ReminderService.GetTaskInCache:input_type -> services.GetTaskRequest
	3, // 3: services.ReminderService.UpdateDeadLine:output_type -> services.ReminderListRespose
	3, // 4: services.ReminderService.GetTaskInCache:output_type -> services.ReminderListRespose
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reminderService_proto_init() }
func file_reminderService_proto_init() {
	if File_reminderService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reminderService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reminderService_proto_goTypes,
		DependencyIndexes: file_reminderService_proto_depIdxs,
		MessageInfos:      file_reminderService_proto_msgTypes,
	}.Build()
	File_reminderService_proto = out.File
	file_reminderService_proto_rawDesc = nil
	file_reminderService_proto_goTypes = nil
	file_reminderService_proto_depIdxs = nil
}
